name: kebab_OFRP Builder
on:
  workflow_dispatch:
    inputs:
      crypto:
        description: "是否禁用加密模块，true or false"
        required: false
        default: "false"

env:
  Rec_name: Ofox
  Rec_ver: R11.0
  Rec_url: https://github.com/RC1844/platform_manifest_twrp_omni.git -b fox-10.0
  device: kebab
  DT_url: https://github.com/seimo-official/OFRP_oneplis_kebab_device.git
  DT_path: device/oneplus/kebab
  device_path: device/onelpus
  target: recoveryimage
  WorkSpace: WorkSpace
  TZ: Asia/Shanghai
  Author: deimo
  Enable_cache: false
  Enable_ccache: true
  Delete_old: false

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Delete old environment
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          docker rmi `docker images -q`
          sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*

      - name: Initializing environment
        run: |
          sudo -E apt-get clean
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install curl libstdc++6 git wget repo rsync aria2
          git config --global user.name "RC1844"
          git config --global user.email "1844766234@qq.com"
          git clone https://gitlab.com/OrangeFox/misc/scripts --depth=1 --single-branch
          cd scripts
          sudo -E bash setup/android_build_env.sh
          sudo -E bash setup/install_android_sdk.sh

      - name: Sync recovery source
        run: |
          cd /home/runner/
          git clone https://gitlab.com/OrangeFox/sync.git 
          cd sync
          ./get_fox_10.sh ${{env.WorkSpace}}
        # sed -i 's/USE_SSH="1"/USE_SSH="0"/g' get_fox_10.sh
        # ./get_fox_10.sh

      - name: Sync device tree
        run: |
          cd /home/runner/
          mkdir -p ${{env.device_path}}
          cd ${{env.device_path}}
          git clone https://github.com/seimo-official/OFRP_oneplis_kebab_device.git kebab
        # rm -r recovery/root/system/lib64

      - name: Disable Crypto
        if: (github.event.inputs.crypto == 'true' && github.event.inputs.crypto  != 'false') || contains(github.event.action, 'crypto')
        run: |
          cd ${{env.WorkSpace}}/${{ env.DT_path }}
          sed -i 's/TW_INCLUDE_CRYPTO := true/TW_INCLUDE_CRYPTO := false/g' BoardConfig.mk
          sed -i 's/TW_INCLUDE_CRYPTO_FBE := true/TW_INCLUDE_CRYPTO_FBE := false/g' BoardConfig.mk

      - name: Show tree
        run: tree -C -d -L 6
      - name: Restore cache
        uses: actions/cache@v2
        if: env.Enable_cache == 'true' && !cancelled()
        with:
          path: |
            ~/.ccache
            ${{env.WorkSpace}}/out
          key: ${{ runner.os }}-${{env.Rec_name}}-${{env.Rec_ver}}-${{ env.device }}
          restore-keys: |
            ${{ runner.os }}-${{env.Rec_name}}-${{env.Rec_ver}}-${{ env.device }}

      - name: Setup ccache
        uses: alexjurkiewicz/setup-ccache@master
        if: env.Enable_ccache == 'true' && !cancelled()
        with:
          max-size: 5G
          extra-config: |
            keep_comments_cpp = true

      - name: Building ${{env.Rec_name}}
        run: |
          cd ${{env.WorkSpace}}
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          export OF_MAINTAINER="seimo"
          export FOX_VERSION="Unofficial"
          export OF_SCREEN_H=2160
          export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
          lunch omni_${{ env.device }}-eng
          repo sync -j4
          mka ${{env.target}}
        shell: bash

      - name: Get info
        id: info
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d-%H-%M")"
          echo "::set-output name=OutFolder::"${{env.WorkSpace}}/out/target/product/${{ env.device }}""
        shell: bash

      - name: Show out tree
        run: |
          cd ${{steps.info.outputs.OutFolder}}
          sudo zip -r9 ${{env.Rec_name}}_for_${{ env.device }}_by_${{ env.Author }}.zip recovery.img
          tree -C -L 5

      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        # if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{env.Rec_name}}_for_${{ env.device }}-${{ github.run_id }}
          path: ${{steps.info.outputs.OutFolder}}/*.img

      - name: Upload Release
        uses: softprops/action-gh-release@master
        with:
          files: |
            ${{steps.info.outputs.OutFolder}}/${{env.Rec_name}}_for_${{ env.device }}_by_${{ env.Author }}.zip
            ${{steps.info.outputs.OutFolder}}/*.img
          name: ${{env.Rec_name}}-${{ env.device }}-${{ github.run_id }}
          tag_name: ${{ env.device }}-${{env.Rec_name}}-${{ steps.info.outputs.date }}
          body: |
            ${{env.Rec_name}}-${{env.Rec_ver}} for ${{ env.device }} build at ${{ steps.info.outputs.date }}
            Download link :https://download.fastgit.org/RC1844/Actions-Build-TWRP-For-Begonia/releases/download/${{ env.device }}-${{env.Rec_name}}-${{ steps.info.outputs.date }}/${{env.Rec_name}}_for_${{ env.device }}_by_${{ env.Author }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.Delete_old == 'true' && !cancelled()
        with:
          keep_latest: 12
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.OFRP }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        if: env.Delete_old == 'true' && !cancelled()
        with:
          retain_days: 1
          keep_minimum_runs: 10
